os: osx
osx_image: xcode12.2

before_install:
  - chmod +x ./tool/test.sh

sudo: required

before_script:
  - git clone https://github.com/flutter/flutter.git -b stable ../flutter
  - export PATH="$PATH":`pwd`/../flutter/bin
  - export PATH="$PATH":`pwd`/../flutter/bin/cache/dart-sdk/bin
  - flutter config --no-analytics
  - flutter doctor
  - export FLUTTER_SDK=`pwd`/../flutter
  - gem install coveralls-lcov
  - flutter pub global activate dart_style
  - flutter packages get || exit -1;

jobs:
  include:
    - stage: quality
      name: "Tests"
      script: ./tool/test.sh
    - stage: quality
      name: "Analyze"
      script: flutter analyze || exit -1;
    - stage: quality
      name: "Format"
      script: flutter pub global run dart_style:format -n --set-exit-if-changed . || exit -1;

stages:
  - quality

branches:
  only:
    - master
cache:
  directories:
    - $HOME/.pub-cache