name: icapps_architecture
description: icapps architecture components for flutter projects. Contains commonly used code for logging, extensions, ...
homepage: https://github.com/icapps/flutter-icapps-architecture
repository: https://github.com/icapps/flutter-icapps-architecture
issue_tracker: https://github.com/icapps/flutter-icapps-architecture/issues
version: 1.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  computer: ^3.2.1
  connectivity_plus: ^3.0.3
  device_info_plus: ^8.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  logger: ^1.2.2
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  tuple: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_lints: ^2.0.1

flutter: