name: icapps_architecture
description: icapps architecture components for flutter projects. Contains commonly used code for logging, extensions, ...
homepage: https://github.com/icapps/flutter-icapps-architecture
repository: https://github.com/icapps/flutter-icapps-architecture
issue_tracker: https://github.com/icapps/flutter-icapps-architecture/issues
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  computer: ^3.2.1
  connectivity_plus: ^4.0.1
  device_info_plus: ^9.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  logger: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  tuple: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  flutter_lints: ^2.0.1

flutter: