name: icapps_architecture
description: icapps architecture components for flutter projects

version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  connectivity: 2.0.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  provider: ^5.0.0
  mockito: ^5.0.3
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter

flutter: