name: icapps_architecture
description: icapps architecture components for flutter projects. Contains commonly used code for logging, extensions, ...
homepage: https://github.com/icapps/flutter-icapps-architecture
repository: https://github.com/icapps/flutter-icapps-architecture

version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  connectivity: ^3.0.3
  device_info: ^2.0.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  logger: ^1.0.0
  provider: ^5.0.0
  mockito: ^5.0.3
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
  connectivity_platform_interface: ^2.0.0
  device_info_platform_interface: ^2.0.1

flutter: