name: icapps_architecture
description: icapps architecture components for flutter projects. Contains commonly used code for logging, extensions, ...
homepage: https://github.com/icapps/flutter-icapps-architecture
repository: https://github.com/icapps/flutter-icapps-architecture

version: 0.2.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  connectivity_plus: ^1.0.0
  device_info_plus: ^1.0.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  logger: ^1.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3
  connectivity_plus_platform_interface: ^1.0.0
  device_info_plus_platform_interface: ^1.0.1

flutter: