name: Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2.8.0
      with:
        channel: 'stable'
    - run: flutter packages get
    - run: dart format . --set-exit-if-changed